import type { Cake, SpecialOffer, CustomizationOptions, Order, CartItem } from './types';

export const cakes: Cake[] = [
  {
    id: 'red-velvet-delight',
    name: 'Red Velvet Delight',
    description: 'A classic Southern dessert, this cake boasts a moist, velvety crumb with a hint of cocoa, layered with rich cream cheese frosting.',
    base_price: 3200,
    image_id: 'red-velvet-delight',
    rating: 4.8,
    category: 'Classic',
    orders_count: 152,
    ready_time: '24h',
  },
  {
    id: 'strawberry-dream',
    name: 'Strawberry Dream',
    description: 'Light vanilla sponge cake filled with fresh strawberries and whipped cream. A dreamy, refreshing treat for any occasion.',
    base_price: 3000,
    image_id: 'strawberry-dream',
    rating: 4.7,
    category: 'Fruit',
    orders_count: 120,
    ready_time: '24h',
  },
    {
    id: 'chocolate-fudge-bliss',
    name: 'Chocolate Fudge Bliss',
    description: 'A chocoholic\'s dream. Decadent layers of rich chocolate fudge cake and creamy chocolate ganache. Pure bliss.',
    base_price: 3500,
    image_id: 'special-offer-cake', // Re-using special offer image for this
    rating: 4.9,
    category: 'Chocolate',
    orders_count: 210,
    ready_time: '48h',
  },
  {
    id: 'lemon-zest-creation',
    name: 'Lemon Zest Creation',
    description: 'A zesty and tangy lemon cake made with fresh lemon juice and zest, topped with a sweet lemon glaze.',
    base_price: 2800,
    image_id: 'lemon-zest-creation',
    rating: 4.6,
    category: 'Citrus',
    orders_count: 98,
    ready_time: '24h',
  },
  {
    id: 'vanilla-bean-classic',
    name: 'Vanilla Bean Classic',
    description: 'Timeless and elegant. A moist vanilla bean cake with a silky smooth vanilla buttercream frosting. Simply perfect.',
    base_price: 2500,
    image_id: 'vanilla-bean-classic',
    rating: 4.5,
    category: 'Classic',
    orders_count: 180,
    ready_time: '24h',
  },
  {
    id: 'matcha-elegance',
    name: 'Matcha Elegance',
    description: 'A sophisticated cake featuring premium matcha green tea, balanced with a light and airy white chocolate mousse.',
    base_price: 3800,
    image_id: 'matcha-elegance',
    rating: 4.8,
    category: 'Exotic',
    orders_count: 75,
    ready_time: '48h',
  },
];

export const specialOffer: SpecialOffer = {
  cake: {
    id: 'special-offer-cake',
    name: 'Whiskey Delight',
    description: 'Our signature creation. A rich chocolate cake infused with a hint of premium whiskey, layered with a salted caramel buttercream. An unforgettable taste.',
    base_price: 4000,
    image_id: 'special-offer-cake',
    rating: 4.9,
    category: 'Signature',
    orders_count: 88,
    ready_time: '48h',
  },
  discount_percentage: 20,
  original_price: 4000,
  special_price: 3200,
  savings: 800,
};

export const customizationOptions: CustomizationOptions = {
  flavors: [
    { id: 'f1', name: 'Classic Vanilla', description: 'Sweet and aromatic', price: 0, color: '#F3E5AB' },
    { id: 'f2', name: 'Rich Chocolate', description: 'Deep and decadent', price: 200, color: '#5D4037' },
    { id: 'f3', name: 'Zesty Lemon', description: 'Bright and refreshing', price: 150, color: '#FFF59D' },
    { id: 'f4', name: 'Red Velvet', description: 'Classic Southern charm', price: 300, color: '#B71C1C' },
  ],
  sizes: [
    { id: 's1', name: '6" Round', serves: '6-8 people', price: 0 },
    { id: 's2', name: '8" Round', serves: '10-12 people', price: 800 },
    { id: 's3', name: '10" Round', serves: '15-20 people', price: 1500 },
    { id: 's4', name: 'Two-Tier', serves: '25-30 people', price: 4000 },
  ],
  colors: [
    { id: 'c1', name: 'Classic White', hex_value: '#FFFFFF', price: 0 },
    { id: 'c2', name: 'Pastel Pink', hex_value: '#FFCDD2', price: 100 },
    { id: 'c3', name: 'Sky Blue', hex_value: '#BBDEFB', price: 100 },
    { id: 'c4', name: 'Golden Amber', hex_value: '#FFD54F', price: 200 },
    { id: 'c5', name: 'Rich Chocolate', hex_value: '#5D4037', price: 250 },
  ],
  toppings: [
    { id: 't1', name: 'Fresh Berries', price: 400 },
    { id: 't2', name: 'Chocolate Drip', price: 300 },
    { id: 't3', name: 'Macarons (3 pcs)', price: 500 },
    { id: 't4', name: 'Edible Flowers', price: 350 },
    { id: 't5', name: 'Gold Leaf Flakes', price: 600 },
  ],
};

export const customCake: Cake = {
  id: 'custom-cake',
  name: 'Custom Creation',
  description: 'Design your own cake from scratch. Choose your flavor, size, colors, and toppings to create your perfect dessert.',
  base_price: 0,
  image_id: 'custom-cake-placeholder',
  rating: 0,
  category: 'Custom',
  orders_count: 0,
  ready_time: '48h+',
};

export const orders: Order[] = [
  {
    id: 1,
    order_number: 'CP-12345',
    customer_name: 'John Doe',
    customer_phone: '0712345678',
    customer_email: 'john@example.com',
    delivery_method: 'delivery',
    delivery_address: 'Vision Tower, 5th Floor, Muthithi Road',
    total_price: 3200,
    deposit_amount: 2560,
    payment_status: 'paid',
    order_status: 'processing',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'special-offer-cake',
        cakeId: 'special-offer-cake',
        name: 'Whiskey Delight',
        quantity: 1,
        price: 3200,
        image_id: 'special-offer-cake',
      },
    ],
  },
  {
    id: 2,
    order_number: 'CP-67890',
    customer_name: 'Jane Smith',
    customer_phone: '0787654321',
    customer_email: 'jane@example.com',
    delivery_method: 'pickup',
    pickup_location: 'Westlands Branch',
    total_price: 5300,
    deposit_amount: 4240,
    payment_status: 'paid',
    order_status: 'complete',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
       {
        id: 'custom-1662733487299',
        cakeId: 'custom-cake',
        name: 'Custom Creation',
        quantity: 1,
        price: 5300,
        image_id: 'custom-cake-placeholder',
        customizations: {
          flavor: 'f2',
          size: 's3',
          color: 'c2',
          toppings: ['t1', 't2'],
        },
      },
    ],
  },
    {
    id: 3,
    order_number: 'CP-11223',
    customer_name: 'Peter Jones',
    customer_phone: '0711223344',
    customer_email: 'peter@example.com',
    delivery_method: 'delivery',
    delivery_address: '123 Gitanga Road',
    total_price: 5800,
    deposit_amount: 4640,
    payment_status: 'paid',
    order_status: 'processing',
    created_at: new Date().toISOString(),
    items: [
      {
        id: 'red-velvet-delight',
        cakeId: 'red-velvet-delight',
        name: 'Red Velvet Delight',
        quantity: 1,
        price: 3200,
        image_id: 'red-velvet-delight',
      },
       {
        id: 'vanilla-bean-classic',
        cakeId: 'vanilla-bean-classic',
        name: 'Vanilla Bean Classic',
        quantity: 1,
        price: 2600,
        image_id: 'vanilla-bean-classic',
      },
    ],
  },
];
